/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cameratest_JNIMethods */

#ifndef _Included_com_example_cameratest_JNIMethods
#define _Included_com_example_cameratest_JNIMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cameratest_JNIMethods
 * Method:    startink
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_example_cameratest_JNIMethods_startink
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
